name = "Ingenium: Create & Beyond"
author = "Block Buddies"
version = "0.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "36632e91a1df87f6e687cb6c4cc02b73d3c0f504e95b803e9a9ab342eefe1429"

[versions]
fabric = "0.16.3"
minecraft = "1.20.1"
