name = "Create With Friends"
author = "Daniel Richter"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "448e78e24ffe1d0fff331c9d107e8c1f92e1d26c45e7624a168296c71a041622"

[versions]
fabric = "0.16.3"
minecraft = "1.20.1"
