name = "Create With Friends"
author = "Daniel Richter"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "75e10184b5190c13b5941bddb10d9ea4b0b48e1fb89788d03901f982bd2aeabc"

[versions]
fabric = "0.16.3"
minecraft = "1.20.1"
